---
title: "Lab 5"
author: "Dontae Johnson"
date: "2021-02-23"
output: github_document
---
```{r message=FALSE}
library(tidyverse)
iris <- as_tibble(iris)

```

```{r}
Q1 <-
  rename(
    iris,
    sepal_length = Sepal.Length,
    sepal_width = Sepal.Width,
    petal_length = Petal.Length,
    petal_width = Petal.Width,
    species = Species
  )
Q1
```

```{r}
Q2 <-
  mutate(
    Q1,
    sepal_length_cm = sepal_length * 10,
    sepal_width_cm = sepal_width * 10,
    petal_length_cm = petal_length * 10,
    petal_width_cm = petal_width * 10
  )
```

```{r}
Q3 <-
  mutate(Q1,
         sepal_area = sepal_length * sepal_width,
         petal_area = petal_length * petal_width)
Q3.5 <- select(Q3, sepal_area, petal_area)
```

```{r}
summarize(
Q2,
sepal_count=length(sepal_length),
max=max(sepal_length),
min=min(sepal_length),
max-min(sepal_length),
sepal_median=median(sepal_length),
quantile(sepal_length,probs=0.25),
quantile(sepal_length,probs=0.75),
sepal_iqr=IQR(sepal_length))
```

```{r}
Q5<-
 Q2%>%
 group_by(species)%>%
 summarize(
  petal_count=length(petal_width),
  petal_mean=mean(petal_width),
  petal_devation=sd(petal_width),
  petal_variance=var(petal_width), 
  petal_sem=mean(petal_width)/sqrt(n()),
  petal_ci_upper=petal_mean + 2 * petal_sem,
  petal_ci_lower=petal_mean - 2 * petal_sem
  )
```

```{r}
#this is for 6 and 7
ggplot(data=Q2) +
  geom_jitter(mapping = aes(x=species,y=petal_width)) +
  geom_crossbar(data=Q5,
  mapping=aes(x=species, y = petal_mean, ymax = petal_ci_upper, ymin = petal_ci_lower),
  color = "magenta"
  )
```

```{r}
Q8<-select(Q2,petal_length,petal_width,species)
ggplot(data = Q8) +
  geom_point(mapping = aes(x=petal_length, y=petal_width, color=species))
       
```

